image: tiangolo/uvicorn-gunicorn-fastapi:python3.8

.only-app: &only-app
  only:
    refs:
      - master
      - merge_requests
      - commit
    changes:
      - app/**/*

stages:
  - install
  - test

install:app:
  stage: install
  <<: *only-app
  script:
    - pip install --no-cache-dir -r requirements.txt

test:app:
  stage: test
  needs: ["install:app"]
  <<: *only-app
  script:
    - pytest --cov-report term-missing --cov=app app/
  dependencies:
    - install:app
