image: python:3.11

.only-app: &only-app
  only:
    refs:
      - master
      - merge_requests
    changes:
      - app/**/*

stages:
  - test

test:app:
  stage: test
  <<: *only-app
  services:
    - name: postgres:13
      alias: test_db
      command: ["-p", "5430"]
  script:
    - pip install -r requirements.txt
    - pwd
    - ls # for debug
    - cd app/ros_nodes/src/backend_server 
    - pytest --ignore=./test --ignore=./tests/mock --cov-config=.coveragerc --cov-report term-missing --cov=backend_server backend_server/ -s

variables:
  POSTGRES_DB: inf3995    
  POSTGRES_USER: eq102
  POSTGRES_PASSWORD: root
  SQLALCHEMY_DATABASE_HOST: test_db

before_script:
  - export SQLALCHEMY_DATABASE_HOST