version: '3.8'

services:
  fastapi:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - db
    networks:
      - fastapi-network

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: table    
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - fastapi-network

networks:
  fastapi-network:
    driver: bridge

volumes:
  postgres_data:
