version: '3.8'

services:
  fastapi:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - db
    networks:
      - fastapi-network
    volumes:
      - ./app:/src/app 
    command: ["uvicorn", "app.main:app", "--reload","--host", "0.0.0.0", "--port", "80"]
    # command: ["/bin/bash"]

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: inf3995    
      POSTGRES_USER: eq102
      POSTGRES_PASSWORD: root
    networks:
      - fastapi-network

  test_db:
    image: postgres:13
    command: -p 5555
    volumes:
      - postgres_data:/var/lib/postgresql/test_data
    environment:
      POSTGRES_DB: test_inf3995    
      POSTGRES_USER: test_eq102
      POSTGRES_PASSWORD: test_root
    networks:
      - fastapi-network

networks:
  fastapi-network:
    driver: bridge

volumes:
  postgres_data:
