import os
PORT = 8000
RCL_TIMEOUT = 5
RCL_MAX_RETRIES = 3
SQLALCHEMY_DATABASE_HOST = os.getenv("SQLALCHEMY_DATABASE_HOST", "host.docker.internal")
SQLALCHEMY_DATABASE_NAME = "inf3995"
SQLALCHEMY_DATABASE_USER = "eq102"
SQLALCHEMY_DATABASE_PASSWORD = "root"
SQLALCHEMY_DATABASE_URL = f"postgresql://{SQLALCHEMY_DATABASE_USER}:{SQLALCHEMY_DATABASE_PASSWORD}@{SQLALCHEMY_DATABASE_HOST}:5430/{SQLALCHEMY_DATABASE_NAME}"
